export enum LocationType {
  ClearingLine = 1,
  ClearingCardSpot,
  FireStock,
  TreeDecks,
  TreeDeckSpot,
  RecruitmentLine,
  SharedHelpLine,
  PersonalHelpLine,
  VaranDeck,
  SeasonAnimalDeck,
  PlayerForest,
  PlayerActionSupply,
  PlayerFireStock,
  OnibiCard,
  SankiDeck,
  SharedDeck,
  SharedDiscardPile,
  TreeToken,
  ActionToken
}
