export enum LocationType {
  ClearingLine = 1,
  ClearingCardSpot,
  FireStock,
  TreeDeckSpot,
  RecruitmentLine,
  SharedHelpLine,
  VaranDeck,
  SeasonAnimalDeck,
  PlayerHelpLine,
  PlayerSpiritLine,
  PlayerForest,
  PlayerActionSupply,
  PlayerActionLost,
  PlayerFireStock,
  OnibiCard,
  SankiDeck,
  SharedDeck,
  SharedDiscardPile,
  TreeToken,
  ActionToken
}
